# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"] #["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.10.3"
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: |
        uv sync --locked --all-extras --dev
        git clone https://github.com/volodymyrss/nbworkflow-test.git tests/testrepo

    - name: Lint with flake8
      run: |
        uv run flake8 ./nb2workflow --count --select=E9,F63,F7,F82 --show-source --statistics 
        uv run flake8 ./nb2workflow --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        uv run pytest -sv --log-cli-level DEBUG --cov=./ -k 'not cwl and not docker and not deploy'

    - name: Codecov
      uses: codecov/codecov-action@v5

